### ISSUE TITLE
Crash app when zoom in, zoom out in Android

### ISSUE THREAD

**Issue by PHPMSX** [Map4D/map4d-map-flutter#12]
Logs:

F/libc    (27326): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27326 (calchat.example), pid 27326 (calchat.example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/ginkgo/ginkgo:11/RKQ1.201004.002/V12.5.2.0.RCOMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-07-07 17:26:16+0700
pid: 27326, tid: 27326, name: calchat.example  >>> com.mylocalchat.example <<<
uid: 10436
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  0000000000006abe  x2  0000000000000006  x3  0000007fc2d717a0
    x4  284901ff3a425328  x5  284901ff3a425328  x6  284901ff3a425328  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  c210f0226056e82b  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 0000000000000000  x14 000000007ffbffff  x15 0000000000000012
    x16 0000007a5db40948  x17 0000007a5db1f490  x18 0000007a63dae000  x19 0000000000006abe
    x20 0000000000006abe  x21 00000000ffffffff  x22 0000000012c899e0  x23 0000000012cbdf18
    x24 0000000012cbdf18  x25 0000000012c899e0  x26 0000000013024158  x27 0000000000000001
    x28 0000007a62c85000  x29 0000007fc2d71820
    lr  0000007a5dad2ba0  sp  0000007fc2d71780  pc  0000007a5dad2bcc  pst 0000000000000000
backtrace:
      #00 pc 0000000000089bcc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 4ba2121e6580a7f88bce586ed966851c)
      #01 pc 000000000002e770  /system/lib64/libinput.so (android::VelocityTracker::addMovement(android::MotionEvent const*)+784) (BuildId: 0a444efa101bc576db5612efe521eaa5)
      #02 pc 0000000000201df4  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+180) (BuildId: fbfea5dcb866437a69805226249eecb5a272e224)
      #03 pc 000000000203b1cc  /memfd:jit-cache (deleted) (offset 0x2000000) (android.view.VelocityTracker.addMovement+60)
      #04 pc 00000000020350c0  /memfd:jit-cache (deleted) (offset 0x2000000) (android.view.GestureDetector.onTouchEvent+304)
      #05 pc 000000000204a250  /memfd:jit-cache (deleted) (offset 0x2000000) (androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent+64)
      #06 pc 000000000204daa8  /memfd:jit-cache (deleted) (offset 0x2000000) (androidx.core.view.GestureDetectorCompat.onTouchEvent+72)
      #07 pc 000000000204319c  /memfd:jit-cache (deleted) (offset 0x2000000) (vn.map4d.map.core.gestures.StandardScaleGestureDetector.analyzeEvent+300)
      #08 pc 0000000002034c38  /memfd:jit-cache (deleted) (offset 0x2000000) (vn.map4d.map.core.gestures.BaseGesture.analyze+344)
      #09 pc 000000000203852c  /memfd:jit-cache (deleted) (offset 0x2000000) (vn.map4d.map.core.gestures.BaseGesture.onTouchEvent+44)
      #10 pc 0000000002032030  /memfd:jit-cache (deleted) (offset 0x2000000) (vn.map4d.map.core.gestures.AndroidGesturesManager.onTouchEvent+224)
      #11 pc 000000000203cc74  /memfd:jit-cache (deleted) (offset 0x2000000) (vn.map4d.map.core.MapTouchHandler.onTouchEvent+404)
      #12 pc 0000000002025738  /memfd:jit-cache (deleted) (offset 0x2000000) (vn.map4d.map.core.MFMapView.onTouchEvent+312)
      #13 pc 0000000002039e94  /memfd:jit-cache (deleted) (offset 0x2000000) (android.view.View.dispatchTouchEvent+516)
      #14 pc 000000000202fefc  /memfd:jit-cache (deleted) (offset 0x2000000) (android.view.ViewGroup.dispatchTransformedTouchEvent+252)
      #15 pc 0000000002032984  /memfd:jit-cache (deleted) (offset 0x2000000) (android.view.ViewGroup.dispatchTouchEvent+2148)
      #16 pc 0000000002043714  /memfd:jit-cache (deleted) (offset 0x2000000) (io.flutter.plugin.platform.PlatformViewsController$1.onTouch+740)
      #17 pc 0000000002030758  /memfd:jit-cache (deleted) (offset 0x2000000) (io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch+1480)
      #18 pc 00000000020379dc  /memfd:jit-cache (deleted) (offset 0x2000000) (io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall+1228)
      #19 pc 0000000002006738  /memfd:jit-cache (deleted) (offset 0x2000000) (io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage+232)
      #20 pc 00000000020427d4  /memfd:jit-cache (deleted) (offset 0x2000000) (io.flutter.embedding.engine.dart.DartMessenger.invokeHandler+244)
      #21 pc 000000000202dd08  /memfd:jit-cache (deleted) (offset 0x2000000) (io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger+168)
      #22 pc 0000000002044834  /memfd:jit-cache (deleted) (offset 0x2000000) (io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run+132)
      #23 pc 0000000002043c24  /memfd:jit-cache (deleted) (offset 0x2000000) (android.os.Handler.handleCallback+68)
      #24 pc 0000000002046890  /memfd:jit-cache (deleted) (offset 0x2000000) (android.os.Handler.dispatchMessage+64)
      #25 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #26 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #27 pc 0000000000318768  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #28 pc 000000000030ea94  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #29 pc 000000000067c6bc  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #30 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #31 pc 00000000003c824a  /system/framework/framework.jar (offset 0x934000) (android.os.Looper.loop+498)
      #32 pc 0000000000306090  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.829997668608136289)+268) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #33 pc 000000000030e080  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+200) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #34 pc 000000000030f468  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1772) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #35 pc 0000000000177f40  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*)+57848) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #36 pc 000000000013f7d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #37 pc 00000000001a98a4  /system/framework/framework.jar (android.app.ActivityThread.main)
      #38 pc 0000000000306198  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.829997668608136289)+532) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #39 pc 000000000066b3c4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #40 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #41 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #42 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #43 pc 00000000005558c0  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #44 pc 00000000004d5170  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #45 pc 00000000000896f4  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180) (BuildId: 96a2ad2581099975b8c7bb4ab40fb39a7086a166)
      #46 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #47 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #48 pc 0000000000318768  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #49 pc 000000000030ea94  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #50 pc 000000000067c6bc  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #51 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #52 pc 0000000000502b2e  /system/framework/framework.jar (offset 0x1247000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #53 pc 0000000000306090  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.829997668608136289)+268) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #54 pc 000000000066b3c4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #55 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #56 pc 000000000089016c  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2316) (BuildId: fbfea5dcb866437a69805226249eecb5a272e224)
      #57 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #58 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #59 pc 00000000005542fc  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #60 pc 00000000005547b0  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #61 pc 0000000000438f54  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+656) (BuildId: 06dffab2a21982e2bd2effff0158c7cf)
      #62 pc 000000000009d424  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: cbc0a08d6fcd9477e02f865f7931233d)
      #63 pc 00000000000a5364  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+916) (BuildId: cbc0a08d6fcd9477e02f865f7931233d)
      #64 pc 0000000000003680  /system/bin/app_process64 (main+1592) (BuildId: 1ffa62ce1e071ff696118eca58ad6849)
      #65 pc 0000000000085190  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: 4ba2121e6580a7f88bce586ed966851c)

**Comment by sua8051** [comment]
@PHPMSX bạn có thể mô tả chi tiết (version android, model máy...) hơn + step để bị bug vậy không?
