### ISSUE TITLE
Feature request: Add opacity control for overlay feature

### ISSUE THREAD

**Issue by hunghoang** [map4d/map4d-map-flutter#14]
This is a great map for Viet Nam.
It could be perfect if we can control opacity when adding overlay on Map4D with Flutter. Sometimes, when we add an overlay, we want to adjust the opacity of this layer using control.
 Please add this feature to this flutter lib.

Many thanks!

**Comment by omyto** [comment]
Hi @hunghoang,

Transparency (opacity) already support tile overlay in map4d_map v2.4.0

Thanks for your suggestions

**Comment by hunghoang** [comment]
Great! thanks a lot.
