### ISSUE TITLE
##Map 4d marker.

### ISSUE THREAD

**Issue by ManhVu99** [map4d/map4d-map-flutter#20]
**Can I custom marker with my lottie ???**

**Comment by omyto** [comment]
Hiện tại Map4D Marker không hỗ trợ lottiefiles
Tuy nhiên, bạn có thể hiển thị một Widget lên trên bản đồ và thay đổi vị trí của Widget khi map move
Tham khảo [custom_marker_infowindow ](https://github.com/map4d/map4d-map-flutter/tree/master/samples/custom_marker_infowindow)
