### ISSUE TITLE
I got error when pod install. 

### ISSUE THREAD

**Issue by monitork** [map4d/map4d-map-flutter#24]
I'm using macbook m1 
arm64
xcode 14.1
<img width="779" alt="image" src="https://user-images.githubusercontent.com/10239941/216073486-f3004555-8a09-4a15-a608-b52d32999c27.png">

**Comment by omyto** [comment]
> fetch-pack: unexpected disconnect while reading sideband packet

It might be [network issue](https://vnexpress.net/bon-tuyen-cap-quang-bien-cung-dut-4564809.html).

**Comment by monitork** [comment]
@omyto Thank for response, It's correct problem, help me close this issue.
